config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #get "favicon.ico", to: redirect("/assets/favicon.ico")
  root "routes#index"
  get "buses/search"
  get "buses/all_buses"
  get 'tickets/:id/print', to: 'tickets#print', as: :print_ticket, formats: :pdf
  get "tickets/all_bookings"
  get "my_tickets", to: "users#my_tickets"
  get "cancelled_tickets", to: "tickets#cancelled_tickets"
  post "cancel_bus_ticket/:ticket_id", to: "tickets#cancel_ticket", as: "cancel_bus_ticket"
  devise_for :users
  resources :tickets
  resources :buses do
    resources :tickets do
      get "approve_ticket"
      get "reject_ticket"
      get "cancel_ticket"
      get "tickets/send_email"
    end
  end
  resources :routes do
    resources :buses
  end
  resources :schedules
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_footer.html.erb
<div class="card text-center ">
  <div class="card-header">
  </div>
  <div class="card-body">
    <footer class="bg-dark text-white py-3">
      <div class="container ">
        <div class="row">
          <div class="col-md-3 col-sm-6">
            <h5>About Us</h5>
            <ul class="list-unstyled">
              <li><a href="#">ABus on Mobile</a></li>
              <li><a href="#">Sitemap</a></li>
              <li><a href="#">Values</a></li>
              <li><a href="#">Info</a></li>
              <li><a href="#">FAQ</a></li>
              <li><a href="#">Blog</a></li>
            </ul>
          </div>
          <div class="col-md-3 col-sm-6">
            <h5>Contact Us</h5>
            <ul class="list-unstyled">
              <li><a href="#">Bus Operator Registration</a></li>
              <li><a href="#">Agent Registration</a></li>
              <li><a href="#">Insurance Partner</a></li>
              <li><a href="#">User Agreement</a></li>
              <li><a href="#">Global Sites</a></li>
            </ul>
          </div>
          <div class="col-md-3 col-sm-6">
            <h5>Our Partners</h5>
            <ul class="list-unstyled">
              <li><a href="#">Goibibo</a></li>
              <li><a href="#">Makemytrip</a></li>
            </ul>
          </div>
          <div class="col-md-3 col-sm-6">
            <h5>Other Services</h5>
            <ul class="list-unstyled">
              <li><a href="#">Train Tickets</a></li>
              <li><a href="#">Bus Hire</a></li>
              <li><a href="#">Cab Booking</a></li>
              <li><a href="#">Tempo Traveller</a></li>
            </ul>
          </div>
        </div>
        <hr>
        <div class="row">
          <p>&copy; 2023 ABus All rights reserved.</p>
        </div>
      </div>
    </footer>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">ABus</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <% if current_user.try(:admin?) %>
          <li class="nav-item">
            <%=link_to "Add Bus", new_bus_path, class:"nav-link active"%>
          </li>
          <li class="nav-item">
            <%=link_to "Add Route", new_route_path, class:"nav-link active"%>
          </li>
          <li class="nav-item">
            <%=link_to " Add Schedule", new_schedule_path, class:"nav-link active"%>
          </li>
          <li class="nav-item">
            <%=link_to "View Schedules", schedules_path, class:"nav-link active"%>
          </li>
          <li class="nav-item">
            <%=link_to "View All Buses",buses_all_buses_path, class:"nav-link active"%>
          </li>
        <%else%>
        <%end%>
      </ul>
      <div class="d-flex" role="search">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <%if user_signed_in?%>
            <% if current_user.try(:admin?) %>
              <%# if can?(:manage, ticket) %>
              <%= link_to 'All Bookings', tickets_all_bookings_path, class:"btn btn-info"%>
              <%= link_to 'Cancel Tickets', cancelled_tickets_path, class:"btn btn-info"%>
              <%= button_to "Sign out" , destroy_user_session_path, method: :delete ,class:"btn btn-primary"%>
            <%else%>
              <%= link_to 'My Tickets',my_tickets_path(@user) ,class:"btn btn-primary"%>
              <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Profile
                </button>
                <ul class="dropdown-menu dropdown-menu-primary">
                  <li class="dropdown-item"> <%= " welcome "%></li>
                  <li class="dropdown-item"> <%=current_user.name%></li>
                  <li class="dropdown-item"><%=current_user.email%></li>
                  <li class="dropdown-item "><%=link_to "Update Profile",edit_user_registration_path,class:"btn btn-outline-primary"%></li>
                 <li class="dropdown-item "><%= button_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete ,class:"btn btn-outline-primary"%></li>
                </ul>
              </div>
              <%= button_to "Sign out" , destroy_user_session_path, method: :delete ,class:"btn btn-primary"%>
            <%end%>
          <%else%>
            <%= button_to "Sign in" , new_user_session_path, class:"btn btn-primary" %>
            <%= link_to "Sign up" , new_user_registration_path ,class:"btn btn-primary"%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_pagebreaker.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid justify-content-center">
    <span class="navbar-brand mb-0 h1 ">Welcome to AnkitBus Services</span>
  </div>
</nav>

app/views/shared/_slides.html.erb
<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="1500">
      <img src="/assets/indore.jpg" class="d-block w-100 h-500" alt="Bus img">
    </div>
    <div class="carousel-item" data-bs-interval="1500">
      <img src="/assets/dewas.jpg" class="d-block w-100" alt="Bus img">
    </div>
    <div class="carousel-item" data-bs-interval="1500">
      <img src="/assets/bhopal.jpg" class="d-block w-100" alt="Bus img">
    </div>
    <div class="carousel-item" data-bs-interval="1500">
      <img src="/assets/ujjain.jpg" class="d-block w-100" alt="Bus img">
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>