config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #get "favicon.ico", to: redirect("/assets/favicon.ico")
  root "routes#index"
  get "buses/search"
  get "buses/all_buses"
  get 'tickets/:id/print', to: 'tickets#print', as: :print_ticket, formats: :pdf
  get "tickets/all_bookings"
  get "my_tickets", to: "users#my_tickets"
  get "cancelled_tickets", to: "tickets#cancelled_tickets"
  post "cancel_bus_ticket/:ticket_id", to: "tickets#cancel_ticket", as: "cancel_bus_ticket"
  devise_for :users
  resources :tickets
  resources :buses do
    resources :tickets do
      get "approve_ticket"
      get "reject_ticket"
      get "cancel_ticket"
      get "tickets/send_email"
    end
  end
  resources :routes do
    resources :buses
  end
  resources :schedules
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :bus
  belongs_to :user
  belongs_to :route

  validates :name, presence: true, length: { minimum: 2 }
  validates :age, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :user_id, presence: true

  default_scope -> { order(created_at: :desc) }

  enum status: [:Pending, :Confirmed, :Rejected, :Cancelled]
end

app/controllers/tickets_controller.rb
require 'prawn'

class TicketsController < ApplicationController
  authorize_resource

  def index
    @bus = Bus.find(params[:bus_id])
    @tickets = @bus.tickets
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def all_bookings
    @tickets = Ticket.all.order("id DESC")
    #@buses = Bus.all.order("id DESC")
  end

  def new
    @bus = Bus.find_by(id: params[:bus_id])
    @schedule = Schedule.find_by(bus_id: @bus.id)
    if current_user
      @ticket = Ticket.new
    else
      flash[:notice] = "Please sign up or sign in to book a ticket"
      redirect_to new_user_session_path
    end
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    @ticket.status = :Pending
    if @ticket.save
      flash.now[:success] = "ticket save Successfully"
      redirect_to root_path
    else
      render "new"
    end
  end
  def print
  require 'prawn'

  @ticket = Ticket.find(params[:id])

  # Create a new PDF document
  pdf = Prawn::Document.new

  # Add content to the PDF
  pdf.text "Welcome to #{@ticket.bus.name}"
  pdf.move_down 10

  # Show the ticket status based on conditions
  if @ticket.Confirmed?
    pdf.text "Confirmed Ticket", size: 18, color: "00AA00"
  elsif @ticket.Rejected?
    pdf.text "Ticket Not Confirmed", size: 18, color: "FF0000"
  elsif @ticket.Cancelled?
    pdf.text "Cancelled", size: 18, color: "FF0000"
  else
    pdf.text "Ticket Not Confirmed yet - Status pending, please wait...", size: 18, color: "FF0000"
  end
  pdf.move_down 20

  # Add ticket information to the PDF
  pdf.text "Ticket Information", size: 20, style: :bold
  pdf.move_down 10

     pdf.text "Ticket ID: #{@ticket.id}"
     pdf.text "Bus ID: #{@ticket.bus_id}"
     pdf.text " Bus Route: #{@ticket.route.from} to #{@ticket.route.to}"
     pdf.text " Passenger Name: #{@ticket.name}"
     pdf.text "Passenger Age: #{@ticket.age}"
     pdf.text "Bus Far: #{@ticket.price}"
     pdf.text "Pickup Point: #{@ticket.bus.pickup}"
     pdf.text "Drop Point: #{@ticket.bus.drop}"
     pdf.text "Journey Date: #{@ticket.date}"
     pdf.text "Bus Departure Time: #{@ticket.bus.departure_time.strftime("%H:%M")}"
     pdf.text "Bus Arrival Time: #{@ticket.bus.arrival_time.strftime("%H:%M")}"
     pdf.text "Ticket Created At: #{@ticket.created_at}"
     pdf.text "Ticket Updated At: #{@ticket.updated_at}"
     pdf.text "Ticket Status: #{@ticket.status}"



  
  # Add cancel reasons if the ticket is cancelled
  if @ticket.Cancelled?
    pdf.move_down 10
    pdf.text "Cancel Reasons:", size: 16, style: :bold
    pdf.move_down 5
    pdf.text @ticket.cancel_reason
  end

  # Add footer with current date and time
  pdf.move_down 20
  time = Time.now.to_s
  time = DateTime.parse(time).strftime("%d/%m/%Y  %H:%M")
  pdf.text "Generated on: #{time}", align: :center

  # Save or send the PDF as a response to the user's browser
  send_data pdf.render, filename: "ticket.pdf", type: "application/pdf"
end


 def update
    @ticket = Ticket.find(params[:id])
    if @ticket.update(ticket_params)
      flash[:alert] = "detaills updated"
      redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    flash[:alert] = "Ticket deleted"
    redirect_to request.referrer
  end

  def approve_ticket
    @ticket = Ticket.find(params[:ticket_id])
    if @ticket.status != "Confirmed" && @ticket.update(status: :Confirmed)
      bus = Bus.find(@ticket.bus.id)
      bus.seats -= 1
      bus.save
      flash[:alert] = "Ticket has been approved."
      redirect_to request.referrer
      TicketMailer.send_email(@ticket).deliver_now
    else
      redirect_to request.referrer, notice: "Ticket already Confirmed"
    end
  end

  def reject_ticket
    @ticket = Ticket.find(params[:ticket_id])
    if @ticket.status != "Rejected" && @ticket.update(status: :Rejected)
      bus = @ticket.bus
      bus.seats += 1
      bus.save
      flash[:alert] = "Ticket rejected successfully"
      redirect_to request.referrer
      TicketMailer.send_email(@ticket).deliver_now
    else
      redirect_to request.referrer, notice: "Ticket already rejected"
    end
  end

  def cancel_ticket
    @ticket = Ticket.find(params[:ticket_id])
    if @ticket.status != "Cancelled"
      if request.post?
        cancel_reason = params[:cancel_reason]
        @ticket.update(status: "Cancelled", cancel_reason: cancel_reason)
        bus = @ticket.bus
        bus.seats += 1
        bus.save
        redirect_to my_tickets_path, notice: "Ticket was successfully cancelled."
        TicketMailer.send_email(@ticket).deliver_now
      else
        render "tickets/cancel_ticket_form"
      end
    else
      redirect_to request.referrer, notice: "Ticket already cancelled."
    end
  end

  def cancelled_tickets
    @cancelled_tickets = Ticket.where(status: "Cancelled")
  end

  def send_email
    @ticket = Ticket.find(params[:id])
    TicketMailer.send_email(@ticket).deliver_now
  end

  private

  def ticket_params
    params.require(:ticket).permit(:name, :age, :sex, :bus_id, :route_id, :price, :departure_time, :arrival_time, :date)
  end
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/tickets/_ticket_info.html.erb
<div class="container">
    <div class="card text-center">
      <div class="card-header">
        <h3 class="mb-0">Welcome to <%=@ticket.bus.name%></h3>
        <div class="d-flex justify-content-center justify-content-md-end">
          <%if @ticket.Confirmed? %>
            <button type="button" class="btn btn-outline-success">Confirmed Ticket</button>
          <%elsif @ticket.Rejected?%>
            <button type="button" class="btn btn-outline-danger">Ticket Not Confirmed</button>
          <%elsif @ticket.Cancelled?%>
            <button type="button" class="btn btn-outline-danger">Cancelled</button>
          <%else%>
            <button type="button" class="btn btn-outline-danger">Ticket Not Confirmed yet - Status pending please wait...</button>
          <%end%>
        </div>
      </div>
      <div class="card-body">
        <h2 class="mb-3">Ticket Information</h2>
        <div class="table-responsive">
          <table class="table table-bordered table-striped">
            <tbody>
              <tr>
                <th>Ticket ID:</th>
                <td><%= @ticket.id %></td>
              </tr>
              <tr>
                <th>Bus ID:</th>
                <td><%= @ticket.bus_id %></td>
              </tr>
              <tr>
                <th>Bus Route </th>
                <td><%= @ticket.route.from%> to <%= @ticket.route.to%>  </td>
              </tr>
              <tr>
                <th>Passenger Name:</th>
                <td><%= @ticket.name %></td>
              </tr>
              <tr>
                <th>Passenger Age:</th>
                <td><%= @ticket.age %></td>
              </tr>
              <tr>
                <th>Passenger Sex:</th>
                <td><%= @ticket.sex %></td>
              </tr>
              <tr>
                <th>Bus Fare:</th>
                <td><%= @ticket.price %></td>
              </tr>
              <tr>
                <th>Pickup Point:</th>
                <td><%= @ticket.bus.pickup %></td>
              </tr>
              <tr>
                <th>Drop Point:</th>
                <td><%= @ticket.bus.drop %></td>
              </tr>
              <tr>
                <th>Journey Date:</th>
                <td><%= @ticket.date %></td>
              </tr>
              <tr>
                <th>Bus Departure  Time:</th>
                <td><%= @ticket.bus.departure_time.strftime(" %H:%M") %></td>
              </tr>
              <tr>
                <th>Bus Arrival Time:</th>
                <td><%= @ticket.bus.arrival_time.strftime(" %H:%M")%></td>
              </tr>
              <tr>
                <th>Ticket Created At:</th>
                <td><%= @ticket.created_at %></td>
              </tr>
              <tr>
                <th>Ticket Updated At:</th>
                <td><%= @ticket.created_at %></td>
              </tr>
              <tr>
                <th>Ticket Status:</th>
                <td><%= @ticket.status %></td>
              </tr>
              <%if @ticket.Cancelled?%>
                <tr>
                  <th>Cancel Reasons</th>
                  <td><%= @ticket.cancel_reason %></td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer text-muted">
        <%=time = Time.now.to_s 
      time = DateTime.parse(time).strftime("%d/%m/%Y  %H:%M") %>
      </div>
    </div>
  </div>

app/views/tickets/all_bookings.html.erb
<% if @tickets.any? %>
  <h3>All Bus Tickets</h3>
  <table class="table table-bordered table-striped">
    <tr>
      <th>Ticket Id</th>
      <th>Bus Name</th>
      <th>Passenger Name</th>
      <th>Passenger Age</th>
      <th>Destination</th>
      <th>Journey Date</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.id %></td>
        <td><%= ticket.bus.name %></td>
        <td><%= ticket.name %></td>
        <td><%= ticket.age %></td>
        <td><%= ticket.sex %></td>
        <td><%= ticket.date %></td>
        <td><%= ticket.status %></td>
        <td>
          <% if can?(:manage, ticket) %>
            <%= link_to 'Details', ticket_path(ticket), class: "btn btn-info" %>
            <%if ticket.status != "Cancelled"&& ticket.status != "Rejected" && ticket.status != "Confirmed"%>
              <%= link_to "Approve", bus_ticket_approve_ticket_path(ticket.bus_id, ticket), class: "btn btn-success", data: { confirm: "Are you sure you want to approve this ticket?" } %>
              <%= link_to "Reject", bus_ticket_reject_ticket_path(ticket.bus_id, ticket), method: :put, class: "btn btn-warning", data: { confirm: "Are you sure you want to reject this ticket?" } %>
            <%end%>
            <%= link_to "Destroy", ticket_path(ticket), data: {turbo_method: :delete,turbo_confirm: "Are you sure to delete this cancelled ticket?" } , class:"btn btn-danger " %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="d-grid gap-2 col-2 mx-auto">
    <%=link_to "Back", root_path ,class:"btn btn-primary"%>
  </div>
<% else %>
  <h3>No tickets found</h3>
<% end %>

app/views/tickets/cancel_ticket_form.html.erb
<%= form_with(url: cancel_bus_ticket_path(@ticket), method: 'post') do |form| %>
  <div class="form-group">
    <%= form.label :cancel_reason, "Reason for cancellation" %>
    <%= form.text_field :cancel_reason, class: "form-control", required: true %>
  </div>
  <%= form.submit "Cancel ticket", class: "btn btn-danger" %>
<% end %>

app/views/tickets/cancelled_tickets.html.erb
<div class="card-body">
  <% if @cancelled_tickets.present? %>
    <h3>Total Tickets - <%= @cancelled_tickets.count %> </h3>
    <div class="table-responsive">
      <table class="table table-bordered table-striped table-sm">
        <thead class="thead-dark">
          <tr>
            <th>Ticket ID</th>
            <th>Passenger Name</th>
            <th>Passenger Age</th>
            <th>Passenger Sex</th>
            <th>Bus fare</th>
            <th>Ticket status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @cancelled_tickets.each do |ticket| %>
            <tr>
              <td><%= ticket.id %></td>
              <td><%= ticket.name %></td>
              <td><%= ticket.age %></td>
              <td><%= ticket.sex %></td>
              <td><%= ticket.price %></td>
              <td><%= ticket.status %></td>
              <td>
                <%= link_to "View Details", ticket_path(ticket), class:"btn btn-info btn-sm" %>
                <%= link_to "Destroy", ticket_path(ticket), data: {turbo_method: :delete,turbo_confirm: "Are you sure to delete this cancelled ticket?" } , class:"btn btn-danger btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="d-grid gap-2 col-2 mx-auto">
    <%=link_to "Back", root_path ,class:"btn btn-primary"%>
  </div>
<%else%>
  <h1>No cancel tickets </h1>
<%end%>

app/views/tickets/index.html.erb
<% if current_user.try(:admin?) %>
  <div class="card text-center">
    <div class="card-header">
      <h1>View <%= @bus.name %> Bookings</h1>
    </div>
    <div class="card-body">
      <% if @bus.tickets.present? %>
        <h3>Total Tickets - <%= @bus.tickets.count %> </h3>
        <div class="table-responsive">
          <table class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>Ticket ID</th>
                <th>Passenger Name</th>
                <th>Passenger Age</th>
                <th>Passenger Sex</th>
                <th>Bus fare</th>
                <!-- <th>Journey Date</th> -->
                <th>Ticket status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @tickets.each do |ticket| %>
                <tr>
                 <td><%= ticket.id %></td>
                  <td><%= ticket.name %></td>
                  <td><%= ticket.age %></td>
                  <td><%= ticket.sex %></td>
                  <td><%= ticket.price %></td>
                  <td><%= ticket.date %></td>
                  <td><%= ticket.status %></td>
                  <td>
                    <%= link_to 'Details', ticket_path(ticket), class: "btn btn-info" %>
                    <%if ticket.status != "Cancelled"&& ticket.status != "Rejected" && ticket.status != "Confirmed"%>
                      <%= link_to "Approve", bus_ticket_approve_ticket_path(ticket.bus_id, ticket), class: "btn btn-success", data: { confirm: "Are you sure you want to approve this ticket?" } %>
                      <%= link_to "Reject", bus_ticket_reject_ticket_path(ticket.bus_id, ticket), method: :put, class: "btn btn-danger", data: { confirm: "Are you sure you want to reject this ticket?" } %>
                    <%end%>
                    <%= link_to "Destroy", ticket_path(ticket), data: {turbo_method: :delete,turbo_confirm: "Are you sure to delete this cancelled ticket?" } , class:"btn btn-danger " %>
                  <%end%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="d-grid gap-2 col-2 mx-auto">
      <%=link_to "Back", :back ,class:"btn btn-primary"%>
    </div>
  <% else %>
    <p>You have no tickets.</p>
  </div>
<% end %>

app/views/tickets/new.html.erb
<h1> Enter Passenger Details </h1>
<div class="container">
  <%= form_with model: [@bus, @ticket]  do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name, "Enter Passenger Name" %>
    <%= f.text_field :name, class: 'form-control' ,required: true%>
    <%= f.label :age,"Enter Passenger Age" %>
    <%= f.text_field :age, class: 'form-control', required: true%><br>
    <%= f.label :sex,"Enter Passenger Sex "%>
    <%= f.select :sex,  ['Male', 'Female', 'Other'], class: 'form-control', required: true%>
    <%#= f.label :date, "Journey date" %>
    <%#= f.date_field :date, value: params[:date] ,readOnly: true%>
    <%= f.hidden_field :price, value: @bus.price %>
    <%= f.hidden_field :route_id, value: @schedule.route.id %>
    <%= f.hidden_field :bus_id, value: @bus.id %>
    <%= f.hidden_field :departure_time, value: @bus.departure_time%>
    <%= f.hidden_field :arrival_time, value: @bus.arrival_time %>
    <div class="form-group">
      <%= f.submit "Save Passenger Details", class: "btn btn-primary" %>
        <%= link_to "Back", :back ,class:"btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/tickets/show.html.erb
 <%if user_signed_in?%>
  <div class="container">
    <div class="card text-center">
      <div class="card-header">
        <h3 class="mb-0">Welcome to <%=@ticket.bus.name%></h3>
        <div class="d-flex justify-content-center justify-content-md-end">
          <%if @ticket.Confirmed? %>
            <button type="button" class="btn btn-outline-success">Confirmed Ticket</button>
          <%elsif @ticket.Rejected?%>
            <button type="button" class="btn btn-outline-danger">Ticket Not Confirmed</button>
          <%elsif @ticket.Cancelled?%>
            <button type="button" class="btn btn-outline-danger">Cancelled</button>
          <%else%>
            <button type="button" class="btn btn-outline-danger">Ticket Not Confirmed yet - Status pending please wait...</button>
          <%end%>
        </div>
      </div>
      <div class="card-body">
        <h2 class="mb-3">Ticket Information</h2>
        <div class="table-responsive">
          <table class="table table-bordered table-striped">
            <tbody>
              <tr>
                <th>Ticket ID:</th>
                <td><%= @ticket.id %></td>
              </tr>
              <tr>
                <th>Bus ID:</th>
                <td><%= @ticket.bus_id %></td>
              </tr>
              <tr>
                <th>Bus Route </th>
                <td><%= @ticket.route.from%> to <%= @ticket.route.to%>  </td>
              </tr>
              <tr>
                <th>Passenger Name:</th>
                <td><%= @ticket.name %></td>
              </tr>
              <tr>
                <th>Passenger Age:</th>
                <td><%= @ticket.age %></td>
              </tr>
              <tr>
                <th>Passenger Sex:</th>
                <td><%= @ticket.sex %></td>
              </tr>
              <tr>
                <th>Bus Fare:</th>
                <td><%= @ticket.price %></td>
              </tr>
              <tr>
                <th>Pickup Point:</th>
                <td><%= @ticket.bus.pickup %></td>
              </tr>
              <tr>
                <th>Drop Point:</th>
                <td><%= @ticket.bus.drop %></td>
              </tr>
              <tr>
                <th>Journey Date:</th>
                <td><%= @ticket.date %></td>
              </tr>
              <tr>
                <th>Bus Departure  Time:</th>
                <td><%= @ticket.bus.departure_time.strftime(" %H:%M") %></td>
              </tr>
              <tr>
                <th>Bus Arrival Time:</th>
                <td><%= @ticket.bus.arrival_time.strftime(" %H:%M")%></td>
              </tr>
              <tr>
                <th>Ticket Created At:</th>
                <td><%= @ticket.created_at %></td>
              </tr>
              <tr>
                <th>Ticket Updated At:</th>
                <td><%= @ticket.created_at %></td>
              </tr>
              <tr>
                <th>Ticket Status:</th>
                <td><%= @ticket.status %></td>
              </tr>
              <%if @ticket.Cancelled?%>
                <tr>
                  <th>Cancel Reasons</th>
                  <td><%= @ticket.cancel_reason %></td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer text-muted">
        <%=time = Time.now.to_s 
      time = DateTime.parse(time).strftime("%d/%m/%Y  %H:%M") %>
      </div>
    </div>
    <div class="d-flex justify-content-center justify-content-md-end mt-3">
      <div class="d-grid gap-2 d-md-block">
        <%=link_to "Print Ticket", print_ticket_path(@ticket),class:"btn btn-primary mr-md-2"%>
        <%=link_to "Back", :back ,class:"btn btn-primary"%>
      </div>
    </div>
  </div>
<%else%>
  <h1>Please Sign up or Sign in</h1>
<%end%>