config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #get "favicon.ico", to: redirect("/assets/favicon.ico")
  root "routes#index"
  get "buses/search"
  get "buses/all_buses"
  get 'tickets/:id/print', to: 'tickets#print', as: :print_ticket, formats: :pdf
  get "tickets/all_bookings"
  get "my_tickets", to: "users#my_tickets"
  get "cancelled_tickets", to: "tickets#cancelled_tickets"
  post "cancel_bus_ticket/:ticket_id", to: "tickets#cancel_ticket", as: "cancel_bus_ticket"
  devise_for :users
  resources :tickets
  resources :buses do
    resources :tickets do
      get "approve_ticket"
      get "reject_ticket"
      get "cancel_ticket"
      get "tickets/send_email"
    end
  end
  resources :routes do
    resources :buses
  end
  resources :schedules
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :schedules
  has_many :buses, :through => :schedules ,dependent: :destroy
  validates :from, :to, presence: true
  validate :start_and_end_points_are_unique
  self.per_page = 12
  default_scope -> { order(created_at: :desc) }

  def display_name
    "#{from} -  #{to}"
  end

  private

  def start_and_end_points_are_unique
    if from == to
      errors.add(:to, "can't be the same as the start point")
    elsif Route.exists?(from: from, to: to)
      errors.add(:to, "route already exists ")
    end
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  load_and_authorize_resource

  def new
    @route = Route.new
  end

  def index
    @routes = Route.paginate(page: params[:page])
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      flash[:alert] = "Route Added Successfully"
      redirect_to root_path
    else
      render "new"
    end
  end

  def show
    @route = Route.find(params[:id])
    @buses = @route.buses.paginate(page: params[:page])
  end

  def edit
    @route = Route.find(params[:id])
  end

  def update
    @route = Route.find(params[:id])
    if @route.update(route_params)
      flash[:alert] = "Route updated"
      redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    Route.find(params[:id]).destroy
    flash[:alert] = "Route deleted"
    redirect_to request.referrer
  end

  private

  def route_params
    params.require(:route).permit(:from, :to)
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_routeform.html.erb
<div class="container my-3">
  <%= form_with model: @route, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :from,"Enter Starting City" %>
    <%= f.text_field :from, class: 'form-control', required: true %><br>
    <%= f.label :to, "Enter Destination City" %>
    <%= f.text_field :to, class: 'form-control', required: true %><br>
    <%= f.submit "Save Bus Route", class: "btn btn-primary" %>
      <%= link_to "Back", :back ,class:"btn btn-primary"%>
  <% end %>
</div>

app/views/routes/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 container my-3">
    <h1>UpdateRoute </h1>
    <%=render 'routeform'%>
  </div>
</div>

app/views/routes/index.html.erb
<%= render 'shared/slides' %>
<%= render partial: "buses/search_form" %>
<%= render 'shared/pagebreaker' %>
<div class="card container my-5">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Route ID</th>
            <th>Starting From</th>
            <th>Destination</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @routes.each do |route| %>
            <tr>
              <td><%= route.id %></td>
              <td><%= route.from %></td>
              <td><%= route.to %></td>
              <td>
                <% if can?(:manage, route) %>
                  <%= link_to "Update Route", edit_route_path(route), class: "btn btn-primary" %>
                  <%= link_to "Delete Route", route_path(route), data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete this route?"}, class: "btn btn-primary" %>
                  <%= link_to "Show all Buses", route_buses_path(route), class: "btn btn-primary" %>
                <% else %>
                  <%= link_to "View Buses", route_buses_path(route), class: "btn btn-primary" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <ul class="pagination justify-content-center">
      <%= will_paginate @routes %>
    </ul>
  </div>
</div>

app/views/routes/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 container my-3">
    <h1>Add New Route </h1>
    <%=render 'routeform'%>
  </div>
</div>

app/views/routes/show.html.erb
<% if @route.buses.any? %>
  <h3 class="mb-3">Total Buses in this Route (<%= @route.buses.count %>)</h3>
  <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Bus Id</th>
          <th>Name</th>
          <th>Bus Number</th>
          <th>Bus Type</th>
          <th>Bus Price</th>
          <th>Seat Availability</th>
          <th>Pickup Point</th>
          <th>Drop Point</th>
          <th>Departure Time</th>
          <th>Arrival Time</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @buses.each do |bus| %>
          <tr>
            <td><%= bus.id %></td>
            <td><%= bus.name %></td>
            <td><%= bus.number %></td>
            <td><%= bus.bustype %></td>
            <td><%= bus.price %></td>
            <td><%= bus.seats %></td>
            <td><%= bus.pickup %></td>
            <td><%= bus.drop %></td>
            <td><%= bus.departure_time %></td>
            <td><%= bus.arrival_time %></td>
            <td>
              <%# if current_user.try(:admin?) %>
              <% if can?(:manage, bus) %>
                <%= link_to "Update", edit_bus_path(bus), class: "btn btn-primary" %>
                <%= link_to "Tickets", bus_tickets_path(bus), class: "btn btn-primary" %>
                <%= link_to "Destroy", bus_path(bus), data: { turbo_method: :delete, turbo_confirm: "Are you sure to delete this bus?" }, class: "btn btn-danger" %>
              <% else %>
                <%= link_to "Book Ticket", new_bus_ticket_path(bus), class: "btn btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <%= will_paginate @buses %>
    </ul>
  </nav>
<% else %>
  <h1>No Bus found in this Route</h1>
<% end %>