config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #get "favicon.ico", to: redirect("/assets/favicon.ico")
  root "routes#index"
  get "buses/search"
  get "buses/all_buses"
  get 'tickets/:id/print', to: 'tickets#print', as: :print_ticket, formats: :pdf
  get "tickets/all_bookings"
  get "my_tickets", to: "users#my_tickets"
  get "cancelled_tickets", to: "tickets#cancelled_tickets"
  post "cancel_bus_ticket/:ticket_id", to: "tickets#cancel_ticket", as: "cancel_bus_ticket"
  devise_for :users
  resources :tickets
  resources :buses do
    resources :tickets do
      get "approve_ticket"
      get "reject_ticket"
      get "cancel_ticket"
      get "tickets/send_email"
    end
  end
  resources :routes do
    resources :buses
  end
  resources :schedules
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
    authorize_resource
    before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def index
    @route = Route.find(params[:route_id])
    @buses = @route.buses.paginate(page: params[:page])
  end

  def all_buses
    @buses = Bus.paginate(page: params[:page])
  end

  def new
    @bus = Bus.new
  end

  def create
    @bus = Bus.new(bus_params)
    if @bus.save
      flash[:alert] = "Bus Added successfully"
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
    @bus = Bus.find(params[:id])
  end

  def update
    @bus = Bus.find(params[:id])
    if @bus.update(bus_params)
      flash[:alert] = "Bus updated"
      redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    Bus.find(params[:id]).destroy
    flash[:alert] = "Bus deleted"
    redirect_to request.referrer
  end

  def search
    @buses = Bus.all
    if params[:from].present?
      @buses = @buses.where(starting_city: params[:from])
    end
    if params[:to].present?
      @buses = @buses.where(destination_city: params[:to])
    end
    if params[:dates].present?
     # @schedule = Schedule.all
      @schedule = Schedule.where(dates: params[:dates])
    end
  end

  private

  def bus_params
    params.require(:bus).permit(:starting_city, :destination_city, :name, :number, :bustype, :price, :seats, :drop, :pickup, :departure_time, :arrival_time)
  end
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_busform.html.erb
<div class="card container my-3 ">
  <%= form_with model: @bus do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name, "Enter Bus Name" %>
    <%= f.text_field :name, class: 'form-control' , required: true%><br>
    <%= f.label :number,"Enter Bus number" %>
    <%= f.text_field :number, class: 'form-control', required: true %><br>
    <%= f.label :bustype,"Select Bus Type "%>
    <%= f.select :bustype,  ['AC' ,'Non-AC', 'Volvo', 'Sleeper' ,'Semi-sleeper','Luxury'], class: 'form-control', required: true%><br>
    <br>
    <%= f.label :price, "Enter Bus Fare" %>
    <%= f.text_field :price, class: 'form-control' , required: true%><br>
    <%= f.label :seats, "Enter Available Seats"%>
    <%= f.text_field :seats, class: 'form-control', required: true %><br>
    <br>
    <%= f.label :pickup,"Enter Pickup Point"%>
    <%= f.text_field :pickup, class: 'form-control', required: true %><br>
    <%= f.label :drop,"Enter Drop Point"%>
    <%= f.text_field :drop, class: 'form-control', required: true %><br>
    <%= f.label :departure_time,"Enter Departure Time"%>
    <%= f.text_field :departure_time, class: 'form-control' , required: true%><br>
    <%= f.label :arrival_time,"Enter Arrival Time"%>
    <%= f.text_field :arrival_time, class: 'form-control', required: true %><br>
    <%= f.submit "Save Bus", class: "btn btn-primary" %>
    <%= link_to "Back", :back ,class:"btn btn-primary"%> <br>
    <br>
  <%end %>
</div>

app/views/buses/_search_form.html.erb
<div class="card text-center">
  <div class="card-header">
    <h2>ABus is an official TSRTC booking partner</h2>
  </div>
  <div class="card-body">
    <%= form_tag buses_search_path, method: :get do %>
      <%= label_tag :from, "Starting City" %>
      <%= text_field_tag :from, params[:from] %>
      <%= label_tag :to, "Destination City" %>
      <%= text_field_tag :to, params[:to] %>
      <%= label_tag :date, "Date of Travel" %>
      <%= text_field_tag :date, params[:date], type: "date" %>
      <%= submit_tag "Search", class: "btn btn-danger btn-block" %>
    <% end %>
  </div>
  <div class="card-footer text-body-secondary">
  </div>
</div>

app/views/buses/all_buses.html.erb
<% if current_user.try(:admin?)  %>
  <h3>Total Buses (<%= @buses.count %>)</h3>
  <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Bus Id</th>
          <th>Name</th>
          <th>Bus Number</th>
          <th>Bus Type</th>
          <th>Bus Price</th>
          <th>Seats </th>
          <th>Pickup Point</th>
          <th>Drop Point</th>
          <th>Departure Time</th>
          <th>Arrival Time</th>
          <th>Dates</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @buses.each do |bus| %>
          <tr>
            <td><%= bus.id %></td>
            <td><%= bus.name %></td>
            <td><%= bus.number %></td>
            <td><%= bus.bustype %></td>
            <td><%= bus.price %></td>
            <td><%= bus.seats %></td>
            <td><%= bus.pickup %></td>
            <td><%= bus.drop %></td>
            <% if bus.departure_time.present? && bus.arrival_time.present? %>
              <td><%= bus.departure_time.strftime('%H:%M') %></td>
              <td><%= bus.arrival_time.strftime('%H:%M') %></td>
            <% else %>
              <td><%= bus.departure_time %></td>
              <td><%= bus.arrival_time %></td>
            <% end %>
            <% if current_user.try(:admin?)  %>
              <td> <%= select_tag "schedule_date", options_for_select(bus.schedules.where(bus_id: bus.id).pluck(:dates).flatten) %></td>
              <td>
                <%= link_to "Update", edit_bus_path(bus), class:"btn btn-primary"%>
                <%= link_to "Bookings", bus_tickets_path(bus), class:"btn btn-primary"%>
                <%= link_to "Destroy", bus_path(bus), data: {turbo_method: :delete,turbo_confirm: "Are you sure to delete this bus?" } , class:"btn btn-danger" %>
              </td>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <%= will_paginate @buses %>
  </ul>
</nav>
<div class="d-grid gap-2 col-2 mx-auto">
  <%=link_to "Back", root_path ,class:"btn btn-primary"%>
</div>
<br>
<% else %>
  <h1>No Bus found </h1>
  <%= link_to "Back", :back ,class:"btn btn-primary"%>
<% end %>

app/views/buses/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 container my-3 ">
    <h1>Update Bus </h1>
    <%=render 'busform'%>
  </div>
</div>

app/views/buses/index.html.erb
<% if @route.buses.any? %>
  <h3>Total Buses in this Route (<%= @route.buses.count %>)</h3>
  <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Bus Id</th>
          <th>Name</th>
          <th>Bus Number</th>
          <th>Bus Type</th>
          <th>Bus Price</th>
          <th>Seats </th>
          <th>Pickup Point</th>
          <th>Drop Point</th>
          <th>Departure Time</th>
          <th>Arrival Time</th>
          <% if current_user.try(:admin?)  %>
            <th>Availability</th>
          <% end %>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @buses.each do |bus| %>
          <tr>
            <td><%= bus.id %></td>
            <td><%= bus.name %></td>
            <td><%= bus.number %></td>
            <td><%= bus.bustype %></td>
            <td><%= bus.price %></td>
            <td><%= bus.seats %></td>
            <td><%= bus.pickup %></td>
            <td><%= bus.drop %></td>
            <% if bus.departure_time.present? && bus.arrival_time.present? %>
              <td><%= bus.departure_time.strftime('%H:%M') %></td>
              <td><%= bus.arrival_time.strftime('%H:%M') %></td>
            <% else %>
              <td><%= bus.departure_time %></td>
              <td><%= bus.arrival_time %></td>
            <% end %>
            <% if current_user.try(:admin?)  %>
              <td> <%= select_tag "schedule_date", options_for_select(bus.schedules.where(route_id: params[:route_id]).pluck(:dates).flatten) %></td>
              <td>
                <%= link_to "Update", edit_bus_path(bus), class:"btn btn-primary"%>
                <%= link_to "Bookings", bus_tickets_path(bus), class:"btn btn-primary"%>
                <%= link_to "Destroy", bus_path(bus), data: {turbo_method: :delete,turbo_confirm: "Are you sure to delete this bus?" } , class:"btn btn-danger" %>
              </td>
            <% else %>
              <td>
                <%= form_with url: new_bus_ticket_path(bus), method: :get do |f| %>
                  <%= f.label :date, "Select a Date" %>
                  <%= f.select :date, options_for_select(bus.schedules.where(route_id: params[:route_id]).pluck(:dates).flatten) %>
                  <%= f.submit "Book Ticket", class:"btn btn-danger"%>
                <% end %>
              </td>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <%= will_paginate @buses %>
  </ul>
</nav>
<div class="d-grid gap-2 col-2 mx-auto">
  <%=link_to "Back", root_path ,class:"btn btn-primary"%>
</div>
<% else %>
  <h1>No Bus found in this Route</h1>
  <%= link_to "Back", :back ,class:"btn btn-primary"%>
<% end %>

app/views/buses/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 container my-3">
    <h1>Add New Bus </h1>
    <%=render 'busform'%>
  </div>
</div>

app/views/buses/search.html.erb
<% if @buses.any? %>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Bus Id</th>
          <th>Bus Starting</th>
          <th>Bus Destination</th>
          <th>Name</th>
          <th>Bus Number</th>
          <th>Bus Type</th>
          <th>Bus Price</th>
          <th>Seat Availability</th>
          <th>Departure Time</th>
          <th>Arrival Time</th>
          <th>Dates Available/Actions</th>
          
        </tr>
      </thead>
      <tbody>
        <% @buses.each do |bus| %>
          <tr>
            <td><%= bus.id %></td>
            <td><%= bus.starting_city %></td>
            <td><%= bus.destination_city %></td>
            <td><%= bus.name %></td>
            <td><%= bus.number %></td>
            <td><%= bus.bustype %></td>
            <td><%= bus.price %></td>
            <td><%= bus.seats %></td>
            <% if bus.departure_time.present? && bus.arrival_time.present? %>
              <td><%= bus.departure_time.strftime('%H:%M') %></td>
              <td><%= bus.arrival_time.strftime('%H:%M') %></td>
            <% else %>
              <td><%= bus.departure_time %></td>
              <td><%= bus.arrival_time %></td>
            <% end %>
            <% if can?(:manage, bus) %>
             <td> <%= select_tag "schedule_date", options_for_select(bus.schedules.where(bus_id: bus.id).pluck(:dates).flatten) %></td>
             <td> <%= link_to "Update", edit_bus_path(bus), class:"btn btn-primary"%>
              <%= link_to "Bookings", bus_tickets_path(bus), class:"btn btn-primary"%>
              <%= link_to "Destroy", bus_path(bus), data: {turbo_method: :delete,turbo_confirm: "Are you sure to delete this bus?" } , class:"btn btn-danger" %></td>
            <%else%>
              <td> <%= form_with url: new_bus_ticket_path(bus), method: :get do |f| %>
                  <%= f.label :date, "Select a Date" %>
                  <%= f.select :date, options_for_select(bus.schedules.where(bus_id: bus.id).pluck(:dates).flatten) %>
              <%=f.submit "Book Ticket", class:"btn btn-danger"%></td>
              </tr>
            <%end%>
            <%end%>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="card-body">
      <h1 >Sorry! No buses found for this route</h1>
    </div>
  <% end %>